### ISSUE TITLE
Image Scraper Crashes when loading a relative path image from a site

### ISSUE THREAD

**Issue by refatK** [andreigue/simpleTrojan#30]
![image](https://user-images.githubusercontent.com/31963426/157770410-f14041f1-9305-491e-95de-ec2775e9a107.png)

Sometimes websites store images as relative paths to the base site instead of using the complete image url. This causes a crash in the program now, so this case need to be handled when scraping images

**Comment by andreigue** [comment]
Turns out even with complete URLs, it still doesn't work (not sure why)

**Comment by andreigue** [comment]
Goal is to get it to work with https://www.nasa.gov/multimedia/imagegallery/iotd.html

**Comment by andreigue** [comment]
> Turns out even with complete URLs, it still doesn't work (not sure why)

The issue was that the HTML was loaded statically, and so that anything loaded dynamically by the JS script in the page's source code is not run. Turns out that most images on websites are loaded dynamically, so statically loading the HTML doesn't get all the information on the website, which includes the images.

To solve the issue, we used the requests_html package, which uses a Chromium web-engine, thus running the scripts and capturing anything you'd expect to see when normally loading the webpage on a browser.
